version: '3.7'

services:
  worker:
    image: droplt-worker:latest
    container_name: worker
    depends_on:
      - redis
      - postgres
      - transmission
    environment:
      - PUBSUB_CHANNEL_CREATE=${PUBSUB_CHANNEL_CREATE}
      - PUBSUB_CHANNEL_UPDATE=${PUBSUB_CHANNEL_UPDATE}
      - PUBSUB_CHANNEL_DELETE=${PUBSUB_CHANNEL_DELETE}
      - JOB_FEED_INTERVAL=${JOB_FEED_INTERVAL}
      - JOB_CLEAN_INTERVAL=${JOB_CLEAN_INTERVAL}
      - TRANSMISSION_URL=http://transmission:9091
      - TRANSMISSION_USER=${TRANSMISSION_USER}
      - TRANSMISSION_PASSWORD=${TRANSMISSION_PASSWORD}
      - POSTGRES_HOST=postgresql://dropltuser:dropltpass@postgres:5432/droplt
      - REDIS_HOST=redis
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./tmp/docker/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./tmp/docker/redis:/data
    ports:
      - 6379:6379
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASSWORD}
    volumes:
      - ./tmp/docker/transmission/downloads:/downloads
      - ./tmp/docker/transmission/config:/config
      - ./tmp/docker/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
