version: '3.7'

services:
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASSWORD}
    volumes:
      - ./tmp/docker/transmission/downloads:/downloads
      - ./tmp/docker/transmission/config:/config
      - ./tmp/docker/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
